openapi: 3.0.3
info:
  title: Coffee Shop Order
  description: Coffee Shop Order API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/v1/coffeeShop/order:
    get:
      summary: Get actual order
      operationId: getActualOrder
      tags:
        - order-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/order/pay:
    get:
      summary: Pay order
      operationId: payOrder
      tags:
        - order-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/order/addProduct/{id}/{amount}:
    post:
      summary: Add product to order
      operationId: addProductToOrder
      tags:
        - order-controller
      parameters:
        - name: id
          in: path
          description: Product id
          required: true
          schema:
            type: integer
            format: int32
        - name: amount
          in: path
          description: Amount of product
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    ErrorDTO:
      $ref: './components.v1.yaml#/components/schemas/ErrorDTO'
    OrderDTO:
      $ref: './components.v1.yaml#/components/schemas/OrderDTO'
    OrderItemDTO:
      $ref: './components.v1.yaml#/components/schemas/OrderItemDTO'
