openapi: 3.0.3
info:
  title: Coffee Shop
  description: Coffee Shop API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  "/api/v1/coffeeShop/products":
    get:
      summary: Get all products
      operationId: getAllProducts
      tags:
        - coffeeShop-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  "/api/v1/coffeeShop/product/{id}":
    get:
      summary: Get product by id
      operationId: getProductById
      tags:
        - coffeeShop-controller
      parameters:
        - name: id
          in: path
          description: Product id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/order:
    get:
      summary: Get actual order
      operationId: getActualOrder
      tags:
        - coffeeShop-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/order/new:
    get:
      summary: Create new order
      operationId: createNewOrder
      tags:
        - coffeeShop-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/order/addProduct/{id}/{amount}:
    post:
      summary: Add product to order
      operationId: addProductToOrder
      tags:
        - coffeeShop-controller
      parameters:
        - name: id
          in: path
          description: Product id
          required: true
          schema:
            type: integer
            format: int32
        - name: amount
          in: path
          description: Amount of product
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/receipt:
    get:
      summary: Get receipt
      operationId: getReceipt
      tags:
        - coffeeShop-controller
      parameters:
        - name: format
          in: query
          required: true
          schema:
            type: string
            enum: [pdf, json]
            default: json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /api/v1/coffeeShop/error:
    get:
      summary: Get error
      operationId: getError
      tags:
        - coffeeShop-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    ResponseDTO:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDTO'
        error:
          $ref: '#/components/schemas/ErrorDTO'
    ProductDTO:
      type: object
      required:
        - id
        - name
        - price
        - isPromotion
        - type
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        price:
          type: number
          format: double
        type:
          type: string
        isPromotion:
          type: boolean
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
            type: string
    OrderDTO:
        type: object
        required:
            - items
            - total
            - amount
        properties:
          items:
            type: array
            items:
                $ref: '#/components/schemas/OrderItemDTO'
          total:
            type: number
            format: double
          amount:
            type: integer
            format: int32
    OrderItemDTO:
        type: object
        required:
            - product
            - amount
            - total
            - isPromotion
            - unitPrice
        properties:
            product:
                $ref: '#/components/schemas/ProductDTO'
            amount:
              type: integer
              format: int32
            total:
              type: number
              format: double
            isPromotion:
              type: boolean
            unitPrice:
                type: number
                format: double
