components:
  schemas:
    ResponseDTO:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDTO'
        error:
          $ref: '#/components/schemas/ErrorDTO'
    ProductDTO:
      type: object
      required:
        - id
        - name
        - price
        - promotion
        - type
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        price:
          type: number
          format: double
        type:
          type: string
        isPromotion:
          type: boolean
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    OrderDTO:
      type: object
      required:
        - id
        - total
        - orderDate
        - complete
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemDTO'
        total:
          type: number
          format: double
        amount:
          type: integer
          format: int32
    OrderItemDTO:
      type: object
      required:
        - product
        - amount
        - total
        - promotion
        - unitPrice
        - price
        - isNew
      properties:
        product:
          $ref: '#/components/schemas/ProductDTO'
        amount:
          type: integer
          format: int32
        total:
          type: number
          format: double
        isPromotion:
          type: boolean
        unitPrice:
          type: number
          format: double
